---
# {{cookiecutter.github_user}}{{cookiecutter.role_name}}/tasks/main.yml

# Determine which distribution specific variable files exists and include them/
#

- name: "Check whether variables for OS family exists"
  stat: path="{{ '{{' }} role_path {{ '}}' }}/vars/{{ '{{' }} ansible_os_family {{ '}}' }}.yml"
  register: file_osfamily_vars
  delegate_to: 127.0.0.1

- name: "Include variables for OS family"
  include_vars: "{{ '{{' }} ansible_os_family {{ '}}' }}.yml"
  when: file_osfamily_vars.stat.exists is defined and file_osfamily_vars.stat.exists


- name: "Check whether variables for distribution exists"
  stat: path="{{ '{{' }} role_path {{ '}}' }}/vars/{{ '{{' }} ansible_distribution {{ '}}' }}.yml"
  register: file_dist_vars
  delegate_to: 127.0.0.1

- name: "Include variables for distribution"
  include_vars: "{{ '{{' }} ansible_distribution {{ '}}' }}.yml"
  when: file_dist_vars.stat.exists is defined and file_dist_vars.stat.exists


- name: "Check whether variables for distribution/version exists"
  stat: path="{{ '{{' }} role_path {{ '}}' }}/vars/{{ '{{' }} ansible_distribution {{ '}}{{' }}ansible_distribution_major_version {{ '}}' }}.yml"
  register: file_dist_version_vars
  delegate_to: 127.0.0.1

- name: "Include variables for distribution/version"
  include_vars: "{{ '{{' }} ansible_distribution {{ '}}{{' }}ansible_distribution_major_version{{ '}}' }}.yml"
  when: file_dist_version_vars.stat.exists is defined and file_dist_version_vars.stat.exists


# Determine which distribution specific task files exists and include them.
#
- name: "Check whether tasks file for OS family exists"
  stat: path="{{ '{{' }} role_path {{ '}}' }}/tasks/{{ '{{' }} ansible_os_family {{ '}}' }}.yml"
  register: file_osfamily_tasks
  delegate_to: 127.0.0.1

- name: "Include tasks for OS family"
  include: "{{ '{{' }} ansible_os_family {{ '}}' }}.yml"
  when: file_osfamily_tasks.stat.exists is defined and file_osfamily_tasks.stat.exists


- name: "Check whether tasks file for distribution exists"
  stat: path="{{ '{{' }} role_path {{ '}}' }}/tasks/{{ '{{' }} ansible_distribution {{ '}}' }}.yml"
  register: file_dist_tasks
  delegate_to: 127.0.0.1

- name: "Include tasks for distribution"
  include: "{{ '{{' }} ansible_distribution {{ '}}' }}.yml"
  when: file_dist_tasks.stat.exists is defined and file_dist_tasks.stat.exists


- name: "Check whether tasks file for distribution/version exists"
  stat: path="{{ '{{' }} role_path {{ '}}' }}/tasks/{{ '{{' }} ansible_distribution {{ '}}{{' }}ansible_distribution_major_version {{ '}}' }}.yml"
  register: file_dist_version_tasks
  delegate_to: 127.0.0.1

- name: "Include tasks for distribution/version"
  include: "{{ '{{' }} ansible_distribution {{ '}}{{' }}ansible_distribution_major_version{{ '}}' }}.yml"
  when: file_dist_version_tasks.stat.exists is defined and file_dist_version_tasks.stat.exists

